#file: .github/workflows/keep-alive.yml
name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 12 */3 * *' # Every 3 days at noon
  workflow_dispatch: # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Keep-Alive Endpoint
        run: |
          curl -X POST https://your-vercel-domain.vercel.app/api/keep-alive \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json"